//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.12 at 10:11:56 PM WAT 
//


package br.com.s2it.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.s2it.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.s2it.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BinaryTreeResponse }
     * 
     */
    public BinaryTreeResponse createBinaryTreeResponse() {
        return new BinaryTreeResponse();
    }

    /**
     * Create an instance of {@link CalculateCRequest }
     * 
     */
    public CalculateCRequest createCalculateCRequest() {
        return new CalculateCRequest();
    }

    /**
     * Create an instance of {@link CalculateCResponse }
     * 
     */
    public CalculateCResponse createCalculateCResponse() {
        return new CalculateCResponse();
    }

    /**
     * Create an instance of {@link BinaryTreeType }
     * 
     */
    public BinaryTreeType createBinaryTreeType() {
        return new BinaryTreeType();
    }

    /**
     * Create an instance of {@link BinaryTreeRequest }
     * 
     */
    public BinaryTreeRequest createBinaryTreeRequest() {
        return new BinaryTreeRequest();
    }

}
